In [3]:
import pandas as pd

In [4]:
# df = pd.read_excel()
# to read csv file
hr = pd.read_csv('C:/Users/pinki/OneDrive/Desktop/Data_science(infosis)/Data/Data/Employees.csv')
hr.head()
# df_json = pd.read_json()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,2003-06-17,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,2005-09-21,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,2001-01-13,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,2006-01-03,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,NaN,103.0,60.0

In [ ]:
'''
1. Find Null Values -> NaN (Not a Number), NaT (Not a Time)
2. Find unwanted values -> Special Character (,./<>?!@#$%^&*()[]{};':") -> Regular Expression (Regex)
'''

'\n1. Find Null Values -> NaN (Not a Number), NaT (Not a Time)\n2. Find unwanted values -> Special Character (,./<>?!@#$%^&*()[]{};\':") -> Regular Expression (Regex)\n'

In [5]:
# to find number of null values in data
# isnull()
hr.isnull().sum()

EMPLOYEE_ID        0
FIRST_NAME         0
LAST_NAME          0
EMAIL              0
PHONE_NUMBER       0
HIRE_DATE          0
JOB_ID             0
SALARY             0
COMMISSION_PCT    76
MANAGER_ID         1
DEPARTMENT_ID      1
dtype: int64

hr.info()

# Drop Null Values

In [ ]:
# dropna()
# delete data row wise
# if we need to change data permanently use -> inplace = True
# use how='any' to drop rows if data has any one or more null records.
# use how = 'all' to drop rows if data must has all null records
# hr.dropna(axis=1, how='all', inplace=False)

# hr.dropna(axis=0, how='any', inplace=False)

In [ ]:
# axis = 0 -> Row
# axis = 1 -> column

In [ ]:
# how = 'any' / 'all'

In [ ]:
# hr = hr.dropna(axis=1, how='any')

# Fill Null Records

In [ ]:
# fillna()
# permanent change -> inplace=True
# mean, median, mode, custom record

In [6]:
mean_commission = hr['COMMISSION_PCT'].mean()
mean_commission

np.float64(0.22285714285714284)

In [7]:
# NumPy -> Numerical Python
# Pandas

In [ ]:
# hr['COMMISSION_PCT'].median()

In [8]:
# round -> int / float
round_mean_com = round(mean_commission, 2)
round_mean_com

np.float64(0.22)

In [9]:
# hr['COMMISSION_PCT'].fillna(round_mean_com, inplace=True)
hr['COMMISSION_PCT'] = hr['COMMISSION_PCT'].fillna(round_mean_com)

In [ ]:
# format -> string
# format_com = f'${mean_commission:,.2f}'

In [10]:
mgr_mode = hr['MANAGER_ID'].mode()[0]
mgr_mode

np.float64(100.0)

In [11]:
dep_mode = hr['DEPARTMENT_ID'].mode()[0]
dep_mode

np.float64(50.0)

In [12]:
hr['MANAGER_ID'] = hr['MANAGER_ID'].fillna(mgr_mode)
hr['DEPARTMENT_ID'] = hr['DEPARTMENT_ID'].fillna(dep_mode)

In [13]:
# Replace() -> String Function
# replace(find, replace_value, regex=False)
hr['PHONE_NUMBER'] = hr['PHONE_NUMBER'].str.replace('.','-', regex=False)

In [14]:
hr['PHONE_NUMBER']

0      515-123-4567
1      515-123-4568
2      515-123-4569
3      590-423-4567
4      590-423-4568
           ...
106    515-123-8181
107    515-123-7777
108    515-123-8888
109    515-123-8080
110    515-123-8181
Name: PHONE_NUMBER, Length: 111, dtype: str

In [16]:
df = pd.read_csv('C:/Users/pinki/OneDrive/Desktop/Data_science(infosis)/Data/Data/HR_Dataset Refresh.csv')
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,Alagbe Trina,10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

In [ ]:
# show all column names
df.columns

Index(['Employee_Name', 'EmpID', 'MarriedID', 'MaritalStatusID', 'GenderID',
       'EmpStatusID', 'DeptID', 'PerfScoreID', 'FromDiversityJobFairID',
       'Salary', 'Termd', 'PositionID', 'Position', 'State', 'Zip', 'DOB',
       'Gender', 'MaritalDesc', 'CitizenDesc', 'HispanicLatino', 'RaceDesc',
       'DateofHire', 'DateofTermination', 'TermReason', 'EmploymentStatus',
       'Department', 'ManagerName', 'ManagerID', 'RecruitmentSource',
       'PerformanceScore', 'EngagementSurvey', 'EmpSatisfaction',
       'SpecialProjectsCount', 'LastPerformanceReview_Date', 'DaysLateLast30',
       'Absences'],
      dtype='object')

In [ ]:
df['Position'].unique()

array(['Production Technician I', 'Sr. DBA', 'Production Technician II',
       'Software Engineer', 'IT Support', 'Data Analyst',
       'Database Administrator', 'Enterprise Architect', 'Sr. Accountant',
       'Production Manager', 'Accountant I', 'Area Sales Manager',
       'Software Engineering Manager', 'BI Director',
       'Director of Operations', 'Sr. Network Engineer', 'Sales Manager',
       'BI Developer', 'IT Manager - Support', 'Network Engineer',
       'IT Director', 'Director of Sales', 'Administrative Assistant',
       'President & CEO', 'Senior BI Developer',
       'Shared Services Manager', 'IT Manager - Infra',
       'Principal Data Architect', 'Data Architect', 'IT Manager - DB',
       'Data Analyst ', 'CIO'], dtype=object)

In [ ]:
columns = ['Position', 'State', 'Gender', 'MaritalDesc', 'CitizenDesc', 'HispanicLatino', 'RaceDesc', 'TermReason',
          'EmploymentStatus', 'Department', 'ManagerName', 'RecruitmentSource', 'PerformanceScore']
for col in columns:
    col_unique = df[col].unique()
    print(col)
    print('-'*55)
    print(f'{col_unique}\n')

Position
-------------------------------------------------------
['Production Technician I' 'Sr. DBA' 'Production Technician II'
 'Software Engineer' 'IT Support' 'Data Analyst' 'Database Administrator'
 'Enterprise Architect' 'Sr. Accountant' 'Production Manager'
 'Accountant I' 'Area Sales Manager' 'Software Engineering Manager'
 'BI Director' 'Director of Operations' 'Sr. Network Engineer'
 'Sales Manager' 'BI Developer' 'IT Manager - Support' 'Network Engineer'
 'IT Director' 'Director of Sales' 'Administrative Assistant'
 'President & CEO' 'Senior BI Developer' 'Shared Services Manager'
 'IT Manager - Infra' 'Principal Data Architect' 'Data Architect'
 'IT Manager - DB' 'Data Analyst ' 'CIO']

State
-------------------------------------------------------
['MA' 'TX' 'CT' 'VA' 'VT' 'AL' 'WA' 'CA' 'OH' 'IN' 'TN' 'NH' 'RI' 'PA'
 'CO' 'NY' 'UT' 'GA' 'FL' 'NC' 'KY' 'ID' 'NV' 'MT' 'OR' 'ND' 'AZ' 'ME']

Gender
-------------------------------------------------------
['M ' 'F']

MaritalDesc
-------------------------------------------------------
['Single' 'Married' 'Divorced' 'Widowed' 'Separated']

CitizenDesc
-------------------------------------------------------
['US Citizen' 'Eligible NonCitizen' 'Non-Citizen']

HispanicLatino
-------------------------------------------------------
['No' 'Yes' 'no' 'yes']

RaceDesc
-------------------------------------------------------
['White' 'Black or African American' 'Two or more races' 'Asian'
 'American Indian or Alaska Native' 'Hispanic']

TermReason
-------------------------------------------------------
['N/A-StillEmployed' 'career change' 'hours' 'return to school'
 'Another position' 'unhappy' 'attendance' 'performance'
 'Learned that he is a gangster' 'retiring' 'relocation out of area'
 'more money' 'military' 'no-call, no-show' 'Fatal attraction'
 'maternity leave - did not return' 'medical issues' 'gross misconduct']

EmploymentStatus
-------------------------------------------------------
['Active' 'Voluntarily Terminated' 'Terminated for Cause']

Department
-------------------------------------------------------
['Production       ' 'IT/IS' 'Software Engineering' 'Admin Offices'
 'Sales' 'Executive Office']

ManagerName
-------------------------------------------------------
['Michael Albert' 'Simon Roup' 'Kissy Sullivan' 'Elijiah Gray'
 'Webster Butler' 'Amy Dunn' 'Alex Sweetwater' 'Ketsia Liebig'
 'Brannon Miller' 'Peter Monroe' 'David Stanley' 'Kelley Spirea'
 'Brandon R. LeBlanc' 'Janet King' 'John Smith' 'Jennifer Zamora'
 'Lynn Daneault' 'Eric Dougall' 'Debra Houlihan' 'Brian Champaigne'
 'Board of Directors']

RecruitmentSource
-------------------------------------------------------
['LinkedIn' 'Indeed' 'Google Search' 'Employee Referral'
 'Diversity Job Fair' 'On-line Web application' 'CareerBuilder' 'Website'
 'Other']

PerformanceScore
-------------------------------------------------------
['Exceeds' 'Fully Meets' 'Needs Improvement' 'PIP']

# Strip()

In [ ]:
# Use of strip is removing white space.
# Strip() -> remove white space in both side.
# lstrip() -> remove white space in left side only.
# rstrip() -> remove white space in right side only.

In [ ]:
for strip_col in columns:
    df[strip_col] = df[strip_col].str.strip()

# Label Encoding

In [ ]:
# map() -> dictionary
hl_dict = {
    'No': 'No',
    'Yes': 'Yes',
    'no': 'No',
    'yes': 'Yes'
}
df['HispanicLatino'] = df['HispanicLatino'].map(hl_dict)

In [ ]:
df.to_csv('cleaned_hr_data.csv', index=False)
# excel -> to_excel

# Feature Engineering

## Split()

In [ ]:
# Split() -> to seperate one single data in multiple column data
# split(find, n=index, expand=True)

In [ ]:
# df['Employee_Name'] = df['Employee_Name'].str.replace(',',' ',regex=False)

In [ ]:
# df[['Last_Name', 'Middle_Name', 'First_Name']] = df['Employee_Name'].str.split(' ', n=2, expand=True)

In [ ]:
last_first = df['Employee_Name'].str.split(',', n=1, expand=True)

In [ ]:
first_middle = last_first[1].str.strip().str.split(' ', n=1, expand=True)

In [ ]:
df['First_Name'] = first_middle[0]
df['Middle_Name'] = first_middle[1]
df['Last_Name'] = last_first[0]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 582 entries, 0 to 581
Data columns (total 39 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               582 non-null    object
 1   EmpID                       582 non-null    int64
 2   MarriedID                   582 non-null    int64
 3   MaritalStatusID             582 non-null    int64
 4   GenderID                    582 non-null    int64
 5   EmpStatusID                 582 non-null    int64
 6   DeptID                      582 non-null    int64
 7   PerfScoreID                 582 non-null    int64
 8   FromDiversityJobFairID      582 non-null    int64
 9   Salary                      582 non-null    int64
 10  Termd                       582 non-null    int64
 11  PositionID                  582 non-null    int64
 12  Position                    582 non-null    object
 13  State                       582 non-null    object
 14  Zip                         582 non-null    int64
 15  DOB                         582 non-null    object
 16  Gender                      582 non-null    object
 17  MaritalDesc                 582 non-null    object
 18  CitizenDesc                 582 non-null    object
 19  HispanicLatino              582 non-null    object
 20  RaceDesc                    582 non-null    object
 21  DateofHire                  582 non-null    object
 22  DateofTermination           196 non-null    object
 23  TermReason                  582 non-null    object
 24  EmploymentStatus            582 non-null    object
 25  Department                  582 non-null    object
 26  ManagerName                 582 non-null    object
 27  ManagerID                   574 non-null    float64
 28  RecruitmentSource           582 non-null    object
 29  PerformanceScore            582 non-null    object
 30  EngagementSurvey            582 non-null    float64
 31  EmpSatisfaction             582 non-null    int64
 32  SpecialProjectsCount        582 non-null    int64
 33  LastPerformanceReview_Date  582 non-null    object
 34  DaysLateLast30              582 non-null    int64
 35  Absences                    582 non-null    int64
 36  First_Name                  582 non-null    object
 37  Middle_Name                 44 non-null     object
 38  Last_Name                   582 non-null    object
dtypes: float64(2), int64(16), object(21)
memory usage: 177.5+ KB

In [ ]:
# python -> string
# numpy -> <U7
# pandas -> object
# date, time -> datetime

In [ ]:
# datetime datatype -> pandas

In [ ]:
'''
Date
-----------------------
format
--------
'%d.%m.%y' -> default
'%d-%m-%y'
mixed

dayfirst=False -> default
dayfirst=True
---------------------
After convert -> Year-Month-Day

Time
----------
---- Hour Minute Second
'%H.%M.%S' -> default
'%H-%M-%S'
mixed

After convert -> Today date Hour:Minute:Second
'''

In [ ]:
# to convert into date time -> to_datetime(date_column)
df['DOB'] = pd.to_datetime(df['DOB'], format='mixed')

In [ ]:
df['DateofHire'] = pd.to_datetime(df['DateofHire'])

In [ ]:
df['DateofTermination'] = pd.to_datetime(df['DateofTermination'])

In [ ]:
df['DateofTermination']

0            NaT
1     2016-06-16
2     2012-09-24
3            NaT
4     2016-09-06
         ...
577   2016-09-06
578          NaT
579          NaT
580          NaT
581          NaT
Name: DateofTermination, Length: 582, dtype: datetime64[ns]

In [ ]:
Date of Termination -> Null
After convert to date time -> NaT
Do we need to clean it?